##### ============================
#####  Основные настройки
##### ============================
set -g prefix C-j
unbind C-b
bind C-j send-prefix

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 5000
set -sg escape-time 10
setw -g mode-keys vi

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"
set -ga terminal-overrides ",alacritty:RGB"


##### ============================
#####  Управление окнами и панелями
##### ============================
unbind c
bind c new-window -c "#{pane_current_path}"
bind-key x kill-pane
bind r source-file ~/.tmux.conf \; display "Reloaded!"


##### ============================
#####  Копирование и вставка
##### ============================
bind y copy-mode

# vi-режим копирования
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi q send-keys -X cancel

# Быстрая вставка из системного буфера Wayland
# bind P run-shell 'set-buffer "$(wl-paste --no-newline --type text)" && paste-buffer'

# Быстрая вставка из системного буфера X11
bind P run-shell "/home/itiro/.tmux/paste_x11.sh | tmux load-buffer - && tmux paste-buffer"


##### ============================
#####  Оформление интерфейса
##### ============================
set -g mode-style "fg=#7aa2f7,bg=#3b4261"
set -g status-style "fg=#a9b1d6,bg=#1a1b26"
set -g status-interval 5

set -g status-left "#[fg=#1a1b26,bg=#7aa2f7,bold]  #S #[fg=#7aa2f7,bg=#1a1b26,nobold]"
set -g status-right "#[fg=#e0af68,bg=#1a1b26]#[fg=#1a1b26,bg=#7aa2f7] #( ~/.tmux/scripts/cpu.sh ) #[fg=#bb9af7,bg=#1a1b26] #( ~/.tmux/scripts/cpu_temp.sh )°C#[fg=#7dcfff,bg=#1a1b26] #( ~/.tmux/scripts/mem.sh )#[fg=#9ece6a,bg=#1a1b26] #(~/.tmux/scripts/net.sh)"

set -g window-status-format "#[fg=#a9b1d6,bg=#1a1b26] #I: #W "
set -g window-status-current-format "#[fg=#1a1b26,bg=#7aa2f7]#[fg=#1a1b26,bg=#7aa2f7] #I: #W #[fg=#7aa2f7,bg=#1a1b26]"


##### ============================
#####  Плагины
##### ============================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'samoshkin/tmux-plugin-sysstat'


##### ============================
#####  Настройки плагинов
##### ============================
set -g color_dark "#1a1b26"
set -g color_secondary "#7aa2f7"

# prefix-highlight
set -g @prefix_highlight_output_prefix '['
set -g @prefix_highlight_output_suffix ']'
set -g @prefix_highlight_fg "$color_dark"
set -g @prefix_highlight_bg "$color_secondary"
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr "fg=$color_dark,bg=$color_secondary"

# sysstat
set -g @sysstat_cpu_color_low "green"
set -g @sysstat_cpu_color_medium "yellow"
set -g @sysstat_cpu_color_stress "red"

set -g @sysstat_mem_color_low "green"
set -g @sysstat_mem_color_medium "yellow"
set -g @sysstat_mem_color_stress "red"

set -g @sysstat_swap_color_low "green"
set -g @sysstat_swap_color_medium "yellow"
set -g @sysstat_swap_color_stress "red"

# battery
set -g @batt_color_full_charge "#[fg=green]"
set -g @batt_color_high_charge "#[fg=green]"
set -g @batt_color_medium_charge "#[fg=yellow]"
set -g @batt_color_low_charge "#[fg=red]"


##### ============================
#####  Запуск TPM
##### ============================
run '~/.tmux/plugins/tpm/tpm'


set -g status-position bottom
set -g status on
set -g status-interval 5
set -g status-justify centre
